const uniq = (items) => {
  const seen = new Set();
  const out = [];
  for (const raw of items || []) {
    const v = String(raw || "").trim();
    if (!v) continue;
    const key = v.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(v);
  }
  return out;
};

export const DEFAULT_STT_DOMAIN_VOCAB = uniq([
  // General software interview
  "software engineering",
  "technical interview",
  "trade-off",
  "edge case",
  "constraints",
  "time complexity",
  "space complexity",
  "Big O",
  "production-ready",
  "clean code",
  "best practices",
  "scalability",
  "reliability",
  "observability",

  // Backend (Node.js/Express)
  "Node.js",
  "Express",
  "REST API",
  "HTTP",
  "HTTPS",
  "TLS",
  "middleware",
  "controller",
  "service layer",
  "repository pattern",
  "MVC",
  "clean architecture",
  "async/await",
  "Promise",
  "event loop",
  "non-blocking I/O",
  "streams",
  "Buffer",
  "cluster",
  "PM2",
  "graceful shutdown",
  "dotenv",
  "configuration management",
  "API versioning",
  "OpenAPI",
  "Swagger",
  "Postman",
  "pagination",
  "cursor pagination",
  "offset pagination",
  "filtering",
  "sorting",
  "idempotency",
  "rate limiting",
  "token bucket",
  "sliding window",
  "caching",
  "Redis",
  "cache-aside",
  "ETag",
  "Cache-Control",
  "gzip",
  "Brotli",

  // Auth & security
  "JWT",
  "access token",
  "refresh token",
  "refresh token rotation",
  "httpOnly cookies",
  "OAuth2",
  "OpenID Connect",
  "RBAC",
  "permissions",
  "bcrypt",
  "Argon2",
  "CORS",
  "Helmet",
  "CSP",
  "HSTS",
  "input validation",
  "Joi",
  "express-validator",
  "sanitization",
  "NoSQL injection",
  "CSRF",
  "XSS",
  "OWASP",

  // Database (MongoDB)
  "MongoDB",
  "Mongoose",
  "schema design",
  "indexing",
  "compound index",
  "TTL index",
  "text index",
  "geospatial index",
  "aggregation pipeline",
  "$match",
  "$group",
  "$lookup",
  "$project",
  "transactions",
  "ACID",
  "replication",
  "sharding",
  "MongoDB Atlas",

  // Testing
  "unit testing",
  "integration testing",
  "Mocha",
  "Chai",
  "Sinon",
  "mocks",
  "stubs",
  "spies",
  "nyc",
  "Istanbul",
  "TDD",
  "BDD",

  // Frontend (React)
  "React",
  "JSX",
  "functional components",
  "hooks",
  "useState",
  "useEffect",
  "useMemo",
  "useCallback",
  "useRef",
  "useContext",
  "useReducer",
  "custom hooks",
  "React.memo",
  "re-render",
  "controlled components",
  "uncontrolled components",
  "forms",
  "React Hook Form",
  "Formik",
  "Yup",
  "accessibility",
  "a11y",
  "ARIA",
  "semantic HTML",
  "keyboard navigation",
  "focus management",
  "Tailwind CSS",
  "CSS Modules",
  "styled-components",
  "responsive design",
  "mobile-first",
  "code splitting",
  "dynamic import",
  "lazy loading",
  "React.lazy",
  "Suspense",
  "tree shaking",
  "Vite",
  "Webpack",
  "ESLint",
  "Prettier",
  "React Router",
  "protected route",
  "Context API",
  "Redux",
  "Redux Toolkit",
  "RTK Query",
  "Zustand",
  "TanStack Query",
  "optimistic update",
  "infinite scroll",
  "virtualization",
  "react-window",

  // Next.js
  "Next.js",
  "SSR",
  "SSG",
  "ISR",
  "App Router",
  "Pages Router",
  "Server Components",
  "Client Components",
  "Server Actions",
  "API Routes",
  "Middleware",
  "Edge Runtime",
  "next/image",
  "Core Web Vitals",
  "LCP",
  "CLS",
  "INP",
  "Lighthouse",

  // System design
  "load balancer",
  "reverse proxy",
  "Nginx",
  "API gateway",
  "CDN",
  "message queue",
  "Kafka",
  "RabbitMQ",
  "Pub/Sub",
  "event-driven architecture",
  "microservices",
  "monolith",
  "service discovery",
  "read replica",
  "consistency",
  "CAP theorem",
  "eventual consistency",
  "SAGA pattern",
  "retry",
  "timeout",
  "circuit breaker",
  "backpressure",

  // DevOps/Cloud (basics)
  "CI/CD",
  "GitHub Actions",
  "Docker",
  "Docker Compose",
  "Kubernetes",
  "AWS",
  "GCP",
  "Terraform",
  "blue-green deployment",
  "canary deployment",

  // DSA patterns
  "two pointers",
  "sliding window",
  "prefix sum",
  "binary search",
  "recursion",
  "backtracking",
  "dynamic programming",
  "memoization",
  "tabulation",
  "BFS",
  "DFS",
  "topological sort",
  "Dijkstra",
  "union find",
  "priority queue",
  "heap",
  "monotonic stack",
  "bit manipulation",
]);

export const getDefaultSttDomainVocabString = () =>
  DEFAULT_STT_DOMAIN_VOCAB.join(", ");
